### Site Settings ###
title: NekotoArts
description: >-
    Technical Artist who loves sharing ideas. Really loves Breath of the Wild.
baseurl: null # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: nekotoarts/nekotoarts.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: YoussefRaafatNasry/portfolYOU # This uses a remote theme, so all the include files etc. are pulled from this repository
open_new_tab: false # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
    - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
    - pages/tags.html
    - pages/404.html
    - pages/index.md

### Author Info ###
author:
    name: NekotoArts
    image: /images/NekotoBranding/NekotoArts logo upscaled alternative.png
    # behance: your_username
    # dribbble          : your_username
    email: nekoto.business@gmail.com
    # facebook: your_username
    github: nekotogd
    # gitlab            : your_username
    # instagram         : your_username
    # kaggle            : your_username
    # linkedin: gregory-dsouza-690367265
    # medium: your_username
    # soundcloud        : your_username
    # spotify           : your_username
    # stackoverflow     : your_user_id
    # tumblr            : your_username.tumblr.com
    twitch: nekotoarts
    twitter: nekotoarts
# vimeo             : your_username
youtube: nekotoarts
# keybase           : your_username

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
    projects:
        output: true
        permalink: /projects/:name
    snippets:
        output: true
        permalink: /snippets/:title

### Disqus ###
disqus:
    shortname: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
    enabled: false # Set true to enable analytics
    google:
        tracking_id: your-google-tracking-id

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
    enabled: false
    username: your_username
    color: "#007bff"
    message: "Thank you for visiting." # Message to be displayed aside from the button for a few seconds.
    description: "Support me on Buy me a coffee!"

### Defaults for collections ###
defaults:
    - scope:
          path: ""
          type: "projects"
      values:
          layout: "page"
    - scope:
          path: ""
          type: "posts"
      values:
          comments: false # Set to true to enable disqus comments
    - scope:
          path: ""
          type: "snippets"
      values:
          layout: "post"

### Exclude from processing ###
exclude:
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - "*.log"

kramdown:
    math_engine: katex
